### ISSUE TITLE
too many cats

### ISSUE THREAD

**Issue by tharkibo** [mozillascience/open-science-leadership-workshop#10]
their tails are getting caught in the gears. meows are distracting the workers

**Comment by abbycabs** [comment]
THERE CAN NEVER BE TOO MANY CATS!

**Comment by tomhohenstein** [comment]
Are we still working on this repo? I noticed today's merge :cat2: 

Tom

**Comment by abbycabs** [comment]
:muscle: :100: 

Still using the guide!

**Comment by tomhohenstein** [comment]
closing this issue - we have sufficient cats  : )
